### ISSUE TITLE
I think I found a way to parse the archive.

### ISSUE THREAD

**Issue by BlameTwo** [tipsypotato/black-myth-wukong-save-editor#1]
Game Science is developed using the C # language for logic, including archiving. Game archiving is encrypted using RPC. I found the C # code used in the game development process of Game Science from the internet Developed with Net Framework 4.7.2 and integrated with UE engine

![image](https://github.com/user-attachments/assets/c7215fa6-a68a-481e-9be9-8ac044d7cdf6)

You should take a look at this repository, it will be very helpful to you:https://github.com/czastack/B1CSharpLoader，

![image](https://github.com/user-attachments/assets/64a8001a-2e64-4150-8b1f-f2a4850f642d)

**Comment by SagarChandra07** [comment]
I think this will help you.

https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA
Archive password: changeme
I put the necessary dlls in the archive

**Comment by BlameTwo** [comment]
> 我想这会对你有帮助。
> 
> https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA 存档密码：changeme 我将必要的 dll 放在了存档中

Why is my Windows reporting a virus?

**Comment by BlameTwo** [comment]
One more thing, there is a complete development process in this repository, and you can develop a game development tool or game helper based on this repository. Anyway, I don't actually have that much time

**Comment by tipsypotato** [comment]
The CSharpLoader is very helpful, will definitely take a look and play around with it!

**Comment by BlameTwo** [comment]
I have analyzed the game save, and the data in this save is too large and related to the PBTable data of the game resource file. Using FModel, I can find a PBTable folder that contains all the basic game data tables. This is too time-consuming


![image](https://github.com/user-attachments/assets/adf62dff-231d-4cb5-8e5a-21cf1f724626)
![image](https://github.com/user-attachments/assets/57519e85-d10b-48d9-9eeb-b992db376ccb)
